FROM php:7.3-apache

COPY php.ini /usr/local/etc/php/php.ini
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
COPY default-ssl.conf /etc/apache2/sites-available/default-ssl.conf

RUN docker-php-ext-install mysqli pdo pdo_mysql json mbstring

RUN apt-get update

# RUN apt-get install -y libgd-dev libpng-dev libjpeg-dev \
#   && docker-php-ext-configure gd --with-png-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
#   && docker-php-ext-install gd

RUN docker-php-ext-configure exif \
  && docker-php-ext-install exif \
  && docker-php-ext-enable exif

RUN apt-get install -y libcurl3-dev \
  && docker-php-ext-install curl

RUN apt-get install -y zlib1g-dev libicu-dev g++ \
  && docker-php-ext-configure intl \
  && docker-php-ext-install intl

RUN apt-get install -y libzip-dev \
  && docker-php-ext-install zip

RUN pecl install xdebug-2.7.2
RUN docker-php-ext-enable xdebug
COPY xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini

RUN pecl install redis
RUN docker-php-ext-enable redis

RUN a2enmod rewrite

#create DocumentRoot to avoid apache crashing before volumes are mounted
RUN mkdir -p /var/www/html

RUN usermod -u 1000 www-data
