version: '3'
services:
    php-apache:
        build: ./docker/php-apache
        volumes:
            - .:/var/www/html
        ports:
            - 80:80
        depends_on:
            - redis
        links:
            - redis
